# SPDX-License-Identifier: GPL-2.0

# required for overlay support
DTC_FLAGS += -@

dtb-y += vkrzv2l-adc.dtbo
dtb-y += vkrzv2l-can.dtbo
dtb-y += vkrzv2l-cm33.dtbo
dtb-y += vkrzv2l-ext-i2c.dtbo
dtb-y += vkrzv2l-ext-spi.dtbo
dtb-y += vkrzv2l-ext-uart2.dtbo
dtb-y += vkrzv2l-hdmi.dtbo
dtb-y += vkrzv2l-lite-audio.dtbo
dtb-y += vkrzv2l-mipi.dtbo

